### ISSUE TITLE
Option to disable corutines

### ISSUE THREAD

**Issue by Frontrider** [CottonMC/json-factory#10]
Gradle kills the `ContentWriter` when the daemon is enabled (it also produces no errors, so it's really confusing). Current workaround is to disable it, but it might be worth having a mode where it does not use corutines.

**Comment by Juuxel** [comment]
https://github.com/CottonMC/json-factory/blob/93b40aaf0e0f1f5d317f67770e6dccc8af9a5533/src/main/kotlin/io/github/cottonmc/jsonfactory/frontend/ContentWriter.kt#L19
Replacing this with a `runBlocking` call should work, but I might need to fix some `launch` calls in that function then.

Edit: Or I could make it `suspend` and replace that with `coroutineScope`, and let the caller decide how to handle it.

**Comment by Frontrider** [comment]
For now, I think a warning for it in the readme could also work.

The main point where the corutines must be there, is the `write` call. I might be wrong, but if that was a separate class, than it could be initialized inside a corutine, or inside a loop directly (it does not need to be a suspending function to create the effect we want, if I'm right about it).

**Comment by Juuxel** [comment]
`write` has to be suspending since it launches IO coroutines to generate content. That's why `writeAll` has to use either:

- `suspend`
- `runBlocking`
- `GlobalScope.launch` (which I don't want to use)

**Comment by Juuxel** [comment]
https://github.com/CottonMC/json-factory/blob/93b40aaf0e0f1f5d317f67770e6dccc8af9a5533/src/main/kotlin/io/github/cottonmc/jsonfactory/frontend/ContentWriter.kt#L42-L65

This part could be moved out, though.

**Comment by Frontrider** [comment]
I see. Than I have to do more research on it. You do you.
